version: "2"

services:
    selenium:
        image: selenium/standalone-chrome:3.4.0-chromium
        ports:
            - 4444:4444
        environment:
            - JAVA_ENV="-Xms1g -Xmx4g"
        shm_size: 256M

    codeception:
        image: php:7.0-cli
        volumes:
            - .:/app
        command: /app/vendor/bin/codecept run acceptance -c /app/codeception.yml --xml --html --steps
